In [1]:
import pandas as pd

In [11]:
df=pd.read_csv('glassdoor_jobs.csv')

In [12]:
df.head(30)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
5,5,Data Scientist,$71K-$119K (Glassdoor est.),CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix"
6,6,Data Scientist,$54K-$93K (Glassdoor est.),Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1
7,7,Data Scientist,$86K-$142K (Glassdoor est.),Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
8,8,Research Scientist,$38K-$84K (Glassdoor est.),SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
9,9,Data Scientist,$120K-$160K (Glassdoor est.),isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel"
10,10,Data Scientist,$126K-$201K (Glassdoor est.),"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1
11,11,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
12,12,Staff Data Scientist - Technology,$106K-$172K (Glassdoor est.),Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon"
13,13,Data Analyst,$46K-$85K (Glassdoor est.),"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
14,14,Data Scientist,$83K-$144K (Glassdoor est.),Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer"
15,15,Data Engineer I,$102K-$190K (Glassdoor est.),This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1
16,16,"Scientist I/II, Biology",$67K-$137K (Glassdoor est.),"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene"
17,17,Customer Data Scientist,$118K-$189K (Glassdoor est.),Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
18,18,Data Scientist - Health Data Analytics,$110K-$175K (Glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
19,19,Data Scientist,$64K-$111K (Glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
20,20,Data Scientist,$81K-$130K (Glassdoor est.),About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack"
21,21,Senior Data Scientist / Machine Learning,$73K-$119K (Glassdoor est.),IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1
22,22,Data Scientist - Quantitative,$86K-$139K (Glassdoor est.),Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1
23,23,Data Scientist,$63K-$105K (Glassdoor est.),Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1
24,24,Data Scientist,-1,JOB CATEGORY:\n\nInformation Services\n\nREQUI...,3.9,Mars\n3.9,Oregon,"Mc Lean, VA",10000+ employees,1911,Company - Private,Food & Beverage Manufacturing,Manufacturing,$10+ billion (USD),-1
25,25,Data Scientist,$109K-$177K (Glassdoor est.),Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton"
26,26,Digital Health Data Scientist,$63K-$110K (Glassdoor est.),ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
27,27,Data Scientist,$75K-$124K (Glassdoor est.),As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1
28,28,Associate Data Analyst,$34K-$61K (Glassdoor est.),"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
29,29,Clinical Data Scientist,$63K-$105K (Glassdoor est.),THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1

In [5]:
#salary parsing
#company name text only
#state field
#age of company
#parsing of job description

In [15]:
df.shape

(956, 15)

In [7]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

## Cleaning Salary

In [18]:
#removing records which don't have salary

# df[df['Salary Estimate']=='-1']   #showing all records with N/A salary

df =df[df['Salary Estimate']!='-1']

In [19]:
df.head(30)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
5,5,Data Scientist,$71K-$119K (Glassdoor est.),CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix"
6,6,Data Scientist,$54K-$93K (Glassdoor est.),Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1
7,7,Data Scientist,$86K-$142K (Glassdoor est.),Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
8,8,Research Scientist,$38K-$84K (Glassdoor est.),SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
9,9,Data Scientist,$120K-$160K (Glassdoor est.),isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel"
10,10,Data Scientist,$126K-$201K (Glassdoor est.),"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1
11,11,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
12,12,Staff Data Scientist - Technology,$106K-$172K (Glassdoor est.),Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon"
13,13,Data Analyst,$46K-$85K (Glassdoor est.),"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
14,14,Data Scientist,$83K-$144K (Glassdoor est.),Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer"
15,15,Data Engineer I,$102K-$190K (Glassdoor est.),This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1
16,16,"Scientist I/II, Biology",$67K-$137K (Glassdoor est.),"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene"
17,17,Customer Data Scientist,$118K-$189K (Glassdoor est.),Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
18,18,Data Scientist - Health Data Analytics,$110K-$175K (Glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
19,19,Data Scientist,$64K-$111K (Glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
20,20,Data Scientist,$81K-$130K (Glassdoor est.),About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack"
21,21,Senior Data Scientist / Machine Learning,$73K-$119K (Glassdoor est.),IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1
22,22,Data Scientist - Quantitative,$86K-$139K (Glassdoor est.),Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1
23,23,Data Scientist,$63K-$105K (Glassdoor est.),Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1
25,25,Data Scientist,$109K-$177K (Glassdoor est.),Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton"
26,26,Digital Health Data Scientist,$63K-$110K (Glassdoor est.),ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
27,27,Data Scientist,$75K-$124K (Glassdoor est.),As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1
28,28,Associate Data Analyst,$34K-$61K (Glassdoor est.),"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
29,29,Clinical Data Scientist,$63K-$105K (Glassdoor est.),THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
30,30,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1

In [20]:
df['Salary Estimate']

0       $53K-$91K (Glassdoor est.)
1      $63K-$112K (Glassdoor est.)
2       $80K-$90K (Glassdoor est.)
3       $56K-$97K (Glassdoor est.)
4      $86K-$143K (Glassdoor est.)
                  ...
950    $58K-$111K (Glassdoor est.)
951    $72K-$133K (Glassdoor est.)
952     $56K-$91K (Glassdoor est.)
953    $95K-$160K (Glassdoor est.)
955    $61K-$126K (Glassdoor est.)
Name: Salary Estimate, Length: 742, dtype: object

In [26]:
#Steps to follow

#get first part of the record (contains salary info)
#replace 'K' and '$'

#create new columns with minimum and maximum range of a salary
#create average

In [24]:
salary=df['Salary Estimate'].apply(lambda x: x.split('(')[0])   #get first part of the record (contains salary info)

In [29]:
minus_Kd=salary.apply(lambda x: x.replace('$','').replace('K',''))     #replace 'K' and '$'

In [47]:
minus_Kd.head(50)  #showing top 50
minus_Kd.tail(50)  #showing bottom 50

print(minus_Kd.to_string())   #showing full data

0                                       53-91
1                                      63-112
2                                       80-90
3                                       56-97
4                                      86-143
5                                      71-119
6                                       54-93
7                                      86-142
8                                       38-84
9                                     120-160
10                                    126-201
11                                     64-106
12                                    106-172
13                                      46-85
14                                     83-144
15                                    102-190
16                                     67-137
17                                    118-189
18                                    110-175
19                                     64-111
20                                     81-130
21                                     73-119
22                                     86-139
23                                     63-105
25                                    109-177
26                                     63-110
27                                     75-124
28                                      34-61
29                                     63-105
30                                      80-90
31                                      56-97
32                                     72-120
33                                     86-143
34                                     93-149
35                                     85-140
36                                     77-135
37                                     82-132
38                                     83-137
39                                    115-180
40                                     74-138
41                                     64-112
43                                     68-129
44                                    110-175
45                                     52-113
46                                     110-150
48            Employer Provided Salary:150-160
49                                    158-211
50                                      20-39
51                                     56-117
52                                      63-99
54                                     68-114
55                                     86-143
56                                      41-95
57                                     86-144
58                                     80-139
59                                      56-95
60                                    120-189
61                                    111-176
62                                      54-93
63                                     71-119
65                                     82-132
66                                     84-146
67                                    107-172
68                                      49-85
70                                     61-109
72                                     88-148
73                                      60-99
75                                      41-72
76                                     96-161
77                                     65-130
78                                      52-81
79                                    139-220
80                                     50-102
81                                     85-139
82                                     74-122
83                                     99-157
84                                     79-222
85                                     57-118
86                                     83-137
87                                     86-141
88                                     94-154
89                                      37-76
90                                    100-160
91                                     55-100
92                                     60-114
93                                      39-68
94                                    106-172
95                                     86-142
96                                     64-107
97                                      31-65
99                                      34-62
101                                   117-231
102                                    64-106
104                                    79-134
105                                     52-93
106                                    55-116
107                                    72-123
108                                    74-124
109                                     40-73
110                                   102-164
112                                    89-153
113                                    61-110
116                                    65-110
117                                    200-275
118                                    68-123
119                                    80-129
120                                     41-72
122                                     39-71
123                                     38-85
124                                   121-193
125                                    54-102
126                                    83-144
127                                   120-160
128                                   102-163
129                                    76-140
130                                    60-101
131                                    82-133
132                                    65-125
136                                    91-148
137                                    95-173
138                                    77-124
139                                    80-135
140                                    85-159
141                                     80-105
142                                     43-81
143                                     29-50
145                                    82-133
146                                     26-55
147                                    61-118
148                                    60-102
150                                   112-182
152                                    64-106
153                                    51-112
154                                   113-223
156                                    72-129
157                                    71-123
158                                    64-106
159                                   118-189
161           Employer Provided Salary:120-145
162                                    80-120
164                                    80-130
166                                    59-115
167                                    71-136
168                                    81-167
169                                     49-85
170                                    60-114
171                                    71-204
172                                    75-125
174                                    77-136
175                                    74-123
177                                     44-78
178                                    65-148
179                                    59-110
180                                    85-134
181                                   124-204
182                                   131-207
183                                   110-174
185                                    52-101
187                                    81-133
188                                   132-211
190                                    73-119
191                                   110-175
192                                    74-140
193                                   100-190
194                                     43-80
197                             17-24 Per Hour
198                                    91-149
199                                     42-82
200                                   116-185
201                                    59-116
202                                     48-95
203                                     31-72
204                                   105-198
205                                    55-100
206                                    98-182
207                                    73-124
208           Employer Provided Salary:200-250
209                             21-34 Per Hour
210                                   117-206
211                                   111-183
212                                     44-78
213                                    81-159
215                                    83-166
216                                   114-182
217                                     42-76
221                                   114-179
223                                    60-123
224                                   100-166
225                                   108-173
226                                     48-93
228                                    54-115
229                                    60-127
230                                    90-179
233                                   138-224
234                                    54-115
235                                    190-220
239                                     35-62
240                             18-25 Per Hour
242                                     39-66
243                                    81-167
245                                     42-86
246                                    69-127
247                             21-34 Per Hour
248                                     40-68
250                                    49-113
251                                    75-140
253                                    86-139
254                                    66-112
255                                    76-125
256                                     44-86
257                             15-25 Per Hour
258                                     53-92
259                                     44-78
260                                    85-134
262                                    59-110
263                                    64-111
264                                    65-120
265                                    60-103
266                                    53-105
267                                   124-204
268                                   131-207
269                                   110-174
270                                     33-62
273                                    52-101
274                                     48-90
275                                     34-64
276                                   132-211
277                                    81-133
278                                     42-76
281                                    66-111
282                                    74-140
284                                    63-110
285                                    63-105
288                                    91-138
289                                   100-190
290                                    62-114
291                                    71-129
292                                     43-80
293                                    74-119
295                                     55-97
296                                      15-16
299                                    61-106
300                                    91-149
302                                   127-199
305                                    74-126
306                                     33-72
307                             17-24 Per Hour
308                                     37-63
309                                    67-119
310                                    72-117
311                                   116-185
312                                    78-126
313                                     42-82
314                                    59-116
316                                    63-105
317                                   109-177
318                                   116-194
319                                     48-95
320                                    83-133
322                                   105-198
323                                     31-72
324                                    98-182
325                                    55-100
326                                     45-82
328                                    83-135
330                                    70-122
331           Employer Provided Salary:200-250
332                                    70-132
333                                    73-124
334                                    54-101
335                                   117-206
337                             21-34 Per Hour
339                                   111-183
341                                    68-112
342                                     42-74
344                                     44-78
346                                    81-159
347                                    95-161
348                                    75-124
349                                    72-120
350                                    76-126
351                                   114-182
352                                   108-176
353                                   130-208
354                                    83-166
355                                     42-76
356                                     37-68
357                                     52-99
358                                   105-173
362                                    71-134
364                                     39-82
366                                   114-179
367                                    88-162
368                                    60-102
369                                   100-166
370                                     55-99
371                                    67-117
372                                    92-150
375                                   116-209
376                                     38-82
377             Employer Provided Salary:85-90
379                                    62-119
380                                    86-143
381                                    93-149
382                                    84-136
383                                    60-123
384                                     52-89
386                                     48-93
387                                     56-97
388                                    65-119
390                                   108-173
391                                    63-101
392                                    54-115
394                                    90-179
396                                   127-202
397                                     31-57
398                                    60-127
399                                    75-143
400                                   105-194
401                                     45-86
403                                    95-154
406                                    80-148
407                                     36-62
409                                    54-115
410                                     50-92
411                                    67-135
412                                    82-132
413                                    85-140
414                                   138-224
415                                     42-80
416                                    190-220
417                                    68-139
419                                     34-92
420                                     54-71
421                                    65-124
425                                     35-62
426                                   109-200
427                             18-25 Per Hour
428                                    61-113
429                                     39-66
430                                     43-86
431                                    74-149
433                                   113-196
434                                    81-167
435                                    97-160
437                             24-39 Per Hour
442                                     42-86
443                                    69-127
444                                   110-175
446                                   102-172
447                                    74-124
448                                     40-68
449                                   108-171
450                                    76-142
452                                   202-306
454                                     49-97
455                                    49-113
456                             21-34 Per Hour
458                                    65-134
459                                     32-59
461                                    87-158
462                                   107-173
463                                     56-99
464    Employer Provided Salary:25-28 Per Hour
466                                    80-155
467                                     43-98
468                                     45-78
469                                     44-96
470                                    50-110
471                                    61-119
472           Employer Provided Salary:100-140
473                                     56-91
476                                    68-114
477           Employer Provided Salary:150-160
479                                   101-158
482                                   125-210
483                                     43-77
485                                   139-221
486                                     44-86
487                                    78-147
488                                    65-110
489                                     37-66
490                                     38-64
491                                     43-82
492                                     90-110
493                                    61-109
494                                    93-151
495                                     52-81
496                                    40-101
497                                    97-180
498                                    81-134
499                                    84-157
500                                    49-113
501                                    68-139
502                                    75-140
505                                   121-203
506                                     52-85
507                                    81-140
508                                     63-99
509                                    110-150
510                                    83-148
512                                    60-101
516                                     31-55
517                                   102-178
518           Employer Provided Salary:110-130
519                                     48-85
520                                    66-123
521                                    92-146
522                             21-29 Per Hour
523                             10-17 Per Hour
524                                   150-239
525                                     52-91
526                                     82-129
528                                    47-101
530                                     49-76
532                                     43-88
533                                   124-199
534                                     52-93
535                                    97-181
537                                   100-173
538                                     53-96
539                                     65-96
540                                     56-95
541                                   111-176
542                                    75-127
543                                    65-119
544                                     56-97
545                                   108-173
546                                    94-139
548                                   176-289
549                                    92-149
550                                    63-101
552                                    54-115
554                                   118-188

In [56]:
#  print(minus_Kd.apply(lambda x: 1 if 'Employer Provided Salary:'.lower() in x.lower() else 0 ).to_string())

df['employer_provided']=minus_Kd.apply(lambda x: 1 if 'Employer Provided Salary:'.lower() in x.lower() else 0 )    #create new columns with employer provided info
df.head()

<ipython-input-56-aae23d7acdc4>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['employer_provided']=minus_Kd.apply(lambda x: 1 if 'Employer Provided Salary:'.lower() in x.lower() else 0 )

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0

In [57]:
df['hourly']=minus_Kd.apply(lambda x: 1 if 'Per Hour'.lower() in x.lower() else 0 )  #create new columns with houlrly info
df.head()

<ipython-input-57-9d4d7d7fcd4c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hourly']=minus_Kd.apply(lambda x: 1 if 'Per Hour'.lower() in x.lower() else 0 )

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0

In [58]:
print(df[['hourly','employer_provided','Salary Estimate']].to_string())

     hourly  employer_provided                            Salary Estimate
0         0                  0                 $53K-$91K (Glassdoor est.)
1         0                  0                $63K-$112K (Glassdoor est.)
2         0                  0                 $80K-$90K (Glassdoor est.)
3         0                  0                 $56K-$97K (Glassdoor est.)
4         0                  0                $86K-$143K (Glassdoor est.)
5         0                  0                $71K-$119K (Glassdoor est.)
6         0                  0                 $54K-$93K (Glassdoor est.)
7         0                  0                $86K-$142K (Glassdoor est.)
8         0                  0                 $38K-$84K (Glassdoor est.)
9         0                  0               $120K-$160K (Glassdoor est.)
10        0                  0               $126K-$201K (Glassdoor est.)
11        0                  0                $64K-$106K (Glassdoor est.)
12        0                  0               $106K-$172K (Glassdoor est.)
13        0                  0                 $46K-$85K (Glassdoor est.)
14        0                  0                $83K-$144K (Glassdoor est.)
15        0                  0               $102K-$190K (Glassdoor est.)
16        0                  0                $67K-$137K (Glassdoor est.)
17        0                  0               $118K-$189K (Glassdoor est.)
18        0                  0               $110K-$175K (Glassdoor est.)
19        0                  0                $64K-$111K (Glassdoor est.)
20        0                  0                $81K-$130K (Glassdoor est.)
21        0                  0                $73K-$119K (Glassdoor est.)
22        0                  0                $86K-$139K (Glassdoor est.)
23        0                  0                $63K-$105K (Glassdoor est.)
25        0                  0               $109K-$177K (Glassdoor est.)
26        0                  0                $63K-$110K (Glassdoor est.)
27        0                  0                $75K-$124K (Glassdoor est.)
28        0                  0                 $34K-$61K (Glassdoor est.)
29        0                  0                $63K-$105K (Glassdoor est.)
30        0                  0                 $80K-$90K (Glassdoor est.)
31        0                  0                 $56K-$97K (Glassdoor est.)
32        0                  0                $72K-$120K (Glassdoor est.)
33        0                  0                $86K-$143K (Glassdoor est.)
34        0                  0                $93K-$149K (Glassdoor est.)
35        0                  0                $85K-$140K (Glassdoor est.)
36        0                  0                $77K-$135K (Glassdoor est.)
37        0                  0                $82K-$132K (Glassdoor est.)
38        0                  0                $83K-$137K (Glassdoor est.)
39        0                  0               $115K-$180K (Glassdoor est.)
40        0                  0                $74K-$138K (Glassdoor est.)
41        0                  0                $64K-$112K (Glassdoor est.)
43        0                  0                $68K-$129K (Glassdoor est.)
44        0                  0               $110K-$175K (Glassdoor est.)
45        0                  0                $52K-$113K (Glassdoor est.)
46        0                  0                 $110K-$150K(Employer est.)
48        0                  1       Employer Provided Salary:$150K-$160K
49        0                  0               $158K-$211K (Glassdoor est.)
50        0                  0                 $20K-$39K (Glassdoor est.)
51        0                  0                $56K-$117K (Glassdoor est.)
52        0                  0                 $63K-$99K (Glassdoor est.)
54        0                  0                $68K-$114K (Glassdoor est.)
55        0                  0                $86K-$143K (Glassdoor est.)
56        0                  0                 $41K-$95K (Glassdoor est.)
57        0                  0                $86K-$144K (Glassdoor est.)
58        0                  0                $80K-$139K (Glassdoor est.)
59        0                  0                 $56K-$95K (Glassdoor est.)
60        0                  0               $120K-$189K (Glassdoor est.)
61        0                  0               $111K-$176K (Glassdoor est.)
62        0                  0                 $54K-$93K (Glassdoor est.)
63        0                  0                $71K-$119K (Glassdoor est.)
65        0                  0                $82K-$132K (Glassdoor est.)
66        0                  0                $84K-$146K (Glassdoor est.)
67        0                  0               $107K-$172K (Glassdoor est.)
68        0                  0                 $49K-$85K (Glassdoor est.)
70        0                  0                $61K-$109K (Glassdoor est.)
72        0                  0                $88K-$148K (Glassdoor est.)
73        0                  0                 $60K-$99K (Glassdoor est.)
75        0                  0                 $41K-$72K (Glassdoor est.)
76        0                  0                $96K-$161K (Glassdoor est.)
77        0                  0                $65K-$130K (Glassdoor est.)
78        0                  0                 $52K-$81K (Glassdoor est.)
79        0                  0               $139K-$220K (Glassdoor est.)
80        0                  0                $50K-$102K (Glassdoor est.)
81        0                  0                $85K-$139K (Glassdoor est.)
82        0                  0                $74K-$122K (Glassdoor est.)
83        0                  0                $99K-$157K (Glassdoor est.)
84        0                  0                $79K-$222K (Glassdoor est.)
85        0                  0                $57K-$118K (Glassdoor est.)
86        0                  0                $83K-$137K (Glassdoor est.)
87        0                  0                $86K-$141K (Glassdoor est.)
88        0                  0                $94K-$154K (Glassdoor est.)
89        0                  0                 $37K-$76K (Glassdoor est.)
90        0                  0               $100K-$160K (Glassdoor est.)
91        0                  0                $55K-$100K (Glassdoor est.)
92        0                  0                $60K-$114K (Glassdoor est.)
93        0                  0                 $39K-$68K (Glassdoor est.)
94        0                  0               $106K-$172K (Glassdoor est.)
95        0                  0                $86K-$142K (Glassdoor est.)
96        0                  0                $64K-$107K (Glassdoor est.)
97        0                  0                 $31K-$65K (Glassdoor est.)
99        0                  0                 $34K-$62K (Glassdoor est.)
101       0                  0               $117K-$231K (Glassdoor est.)
102       0                  0                $64K-$106K (Glassdoor est.)
104       0                  0                $79K-$134K (Glassdoor est.)
105       0                  0                 $52K-$93K (Glassdoor est.)
106       0                  0                $55K-$116K (Glassdoor est.)
107       0                  0                $72K-$123K (Glassdoor est.)
108       0                  0                $74K-$124K (Glassdoor est.)
109       0                  0                 $40K-$73K (Glassdoor est.)
110       0                  0               $102K-$164K (Glassdoor est.)
112       0                  0                $89K-$153K (Glassdoor est.)
113       0                  0                $61K-$110K (Glassdoor est.)
116       0                  0                $65K-$110K (Glassdoor est.)
117       0                  0                 $200K-$275K(Employer est.)
118       0                  0                $68K-$123K (Glassdoor est.)
119       0                  0                $80K-$129K (Glassdoor est.)
120       0                  0                 $41K-$72K (Glassdoor est.)
122       0                  0                 $39K-$71K (Glassdoor est.)
123       0                  0                 $38K-$85K (Glassdoor est.)
124       0                  0               $121K-$193K (Glassdoor est.)
125       0                  0                $54K-$102K (Glassdoor est.)
126       0                  0                $83K-$144K (Glassdoor est.)
127       0                  0               $120K-$160K (Glassdoor est.)
128       0                  0               $102K-$163K (Glassdoor est.)
129       0                  0                $76K-$140K (Glassdoor est.)
130       0                  0                $60K-$101K (Glassdoor est.)
131       0                  0                $82K-$133K (Glassdoor est.)
132       0                  0                $65K-$125K (Glassdoor est.)
136       0                  0                $91K-$148K (Glassdoor est.)
137       0                  0                $95K-$173K (Glassdoor est.)
138       0                  0                $77K-$124K (Glassdoor est.)
139       0                  0                $80K-$135K (Glassdoor est.)
140       0                  0                $85K-$159K (Glassdoor est.)
141       0                  0                  $80K-$105K(Employer est.)
142       0                  0                 $43K-$81K (Glassdoor est.)
143       0                  0                 $29K-$50K (Glassdoor est.)
145       0                  0                $82K-$133K (Glassdoor est.)
146       0                  0                 $26K-$55K (Glassdoor est.)
147       0                  0                $61K-$118K (Glassdoor est.)
148       0                  0                $60K-$102K (Glassdoor est.)
150       0                  0               $112K-$182K (Glassdoor est.)
152       0                  0                $64K-$106K (Glassdoor est.)
153       0                  0                $51K-$112K (Glassdoor est.)
154       0                  0               $113K-$223K (Glassdoor est.)
156       0                  0                $72K-$129K (Glassdoor est.)
157       0                  0                $71K-$123K (Glassdoor est.)
158       0                  0                $64K-$106K (Glassdoor est.)
159       0                  0               $118K-$189K (Glassdoor est.)
161       0                  1       Employer Provided Salary:$120K-$145K
162       0                  0                $80K-$120K (Glassdoor est.)
164       0                  0                $80K-$130K (Glassdoor est.)
166       0                  0                $59K-$115K (Glassdoor est.)
167       0                  0                $71K-$136K (Glassdoor est.)
168       0                  0                $81K-$167K (Glassdoor est.)
169       0                  0                 $49K-$85K (Glassdoor est.)
170       0                  0                $60K-$114K (Glassdoor est.)
171       0                  0                $71K-$204K (Glassdoor est.)
172       0                  0                $75K-$125K (Glassdoor est.)
174       0                  0                $77K-$136K (Glassdoor est.)
175       0                  0                $74K-$123K (Glassdoor est.)
177       0                  0                 $44K-$78K (Glassdoor est.)
178       0                  0                $65K-$148K (Glassdoor est.)
179       0                  0                $59K-$110K (Glassdoor est.)
180       0                  0                $85K-$134K (Glassdoor est.)
181       0                  0               $124K-$204K (Glassdoor est.)
182       0                  0               $131K-$207K (Glassdoor est.)
183       0                  0               $110K-$174K (Glassdoor est.)
185       0                  0                $52K-$101K (Glassdoor est.)
187       0                  0                $81K-$133K (Glassdoor est.)
188       0                  0               $132K-$211K (Glassdoor est.)
190       0                  0                $73K-$119K (Glassdoor est.)
191       0                  0               $110K-$175K (Glassdoor est.)
192       0                  0                $74K-$140K (Glassdoor est.)
193       0                  0               $100K-$190K (Glassdoor est.)
194       0                  0                 $43K-$80K (Glassdoor est.)
197       1                  0           $17-$24 Per Hour(Glassdoor est.)
198       0                  0                $91K-$149K (Glassdoor est.)
199       0                  0                 $42K-$82K (Glassdoor est.)
200       0                  0               $116K-$185K (Glassdoor est.)
201       0                  0                $59K-$116K (Glassdoor est.)
202       0                  0                 $48K-$95K (Glassdoor est.)
203       0                  0                 $31K-$72K (Glassdoor est.)
204       0                  0               $105K-$198K (Glassdoor est.)
205       0                  0                $55K-$100K (Glassdoor est.)
206       0                  0                $98K-$182K (Glassdoor est.)
207       0                  0                $73K-$124K (Glassdoor est.)
208       0                  1       Employer Provided Salary:$200K-$250K
209       1                  0           $21-$34 Per Hour(Glassdoor est.)
210       0                  0               $117K-$206K (Glassdoor est.)
211       0                  0               $111K-$183K (Glassdoor est.)
212       0                  0                 $44K-$78K (Glassdoor est.)
213       0                  0                $81K-$159K (Glassdoor est.)
215       0                  0                $83K-$166K (Glassdoor est.)
216       0                  0               $114K-$182K (Glassdoor est.)
217       0                  0                 $42K-$76K (Glassdoor est.)
221       0                  0               $114K-$179K (Glassdoor est.)
223       0                  0                $60K-$123K (Glassdoor est.)
224       0                  0               $100K-$166K (Glassdoor est.)
225       0                  0               $108K-$173K (Glassdoor est.)
226       0                  0                 $48K-$93K (Glassdoor est.)
228       0                  0                $54K-$115K (Glassdoor est.)
229       0                  0                $60K-$127K (Glassdoor est.)
230       0                  0                $90K-$179K (Glassdoor est.)
233       0                  0               $138K-$224K (Glassdoor est.)
234       0                  0                $54K-$115K (Glassdoor est.)
235       0                  0                 $190K-$220K(Employer est.)
239       0                  0                 $35K-$62K (Glassdoor est.)
240       1                  0           $18-$25 Per Hour(Glassdoor est.)
242       0                  0                 $39K-$66K (Glassdoor est.)
243       0                  0                $81K-$167K (Glassdoor est.)
245       0                  0                 $42K-$86K (Glassdoor est.)
246       0                  0                $69K-$127K (Glassdoor est.)
247       1                  0           $21-$34 Per Hour(Glassdoor est.)
248       0                  0                 $40K-$68K (Glassdoor est.)
250       0                  0                $49K-$113K (Glassdoor est.)
251       0                  0                $75K-$140K (Glassdoor est.)
253       0                  0                $86K-$139K (Glassdoor est.)
254       0                  0                $66K-$112K (Glassdoor est.)
255       0                  0                $76K-$125K (Glassdoor est.)
256       0                  0                 $44K-$86K (Glassdoor est.)
257       1                  0           $15-$25 Per Hour(Glassdoor est.)
258       0                  0                 $53K-$92K (Glassdoor est.)
259       0                  0                 $44K-$78K (Glassdoor est.)
260       0                  0                $85K-$134K (Glassdoor est.)
262       0                  0                $59K-$110K (Glassdoor est.)
263       0                  0                $64K-$111K (Glassdoor est.)
264       0                  0                $65K-$120K (Glassdoor est.)
265       0                  0                $60K-$103K (Glassdoor est.)
266       0                  0                $53K-$105K (Glassdoor est.)
267       0                  0               $124K-$204K (Glassdoor est.)
268       0                  0               $131K-$207K (Glassdoor est.)
269       0                  0               $110K-$174K (Glassdoor est.)
270       0                  0                 $33K-$62K (Glassdoor est.)
273       0                  0                $52K-$101K (Glassdoor est.)
274       0                  0                 $48K-$90K (Glassdoor est.)
275       0                  0                 $34K-$64K (Glassdoor est.)
276       0                  0               $132K-$211K (Glassdoor est.)
277       0                  0                $81K-$133K (Glassdoor est.)
278       0                  0                 $42K-$76K (Glassdoor est.)
281       0                  0                $66K-$111K (Glassdoor est.)
282       0                  0                $74K-$140K (Glassdoor est.)
284       0                  0                $63K-$110K (Glassdoor est.)
285       0                  0                $63K-$105K (Glassdoor est.)
288       0                  0                $91K-$138K (Glassdoor est.)
289       0                  0               $100K-$190K (Glassdoor est.)
290       0                  0                $62K-$114K (Glassdoor est.)
291       0                  0                $71K-$129K (Glassdoor est.)
292       0                  0                 $43K-$80K (Glassdoor est.)
293       0                  0                $74K-$119K (Glassdoor est.)
295       0                  0                 $55K-$97K (Glassdoor est.)
296       0                  0                   $15K-$16K(Employer est.)
299       0                  0                $61K-$106K (Glassdoor est.)
300       0                  0                $91K-$149K (Glassdoor est.)
302       0                  0               $127K-$199K (Glassdoor est.)
305       0                  0                $74K-$126K (Glassdoor est.)
306       0                  0                 $33K-$72K (Glassdoor est.)
307       1                  0           $17-$24 Per Hour(Glassdoor est.)
308       0                  0                 $37K-$63K (Glassdoor est.)
309       0                  0                $67K-$119K (Glassdoor est.)
310       0                  0                $72K-$117K (Glassdoor est.)
311       0                  0               $116K-$185K (Glassdoor est.)
312       0                  0                $78K-$126K (Glassdoor est.)
313       0                  0                 $42K-$82K (Glassdoor est.)
314       0                  0                $59K-$116K (Glassdoor est.)
316       0                  0                $63K-$105K (Glassdoor est.)
317       0                  0               $109K-$177K (Glassdoor est.)
318       0                  0               $116K-$194K (Glassdoor est.)
319       0                  0                 $48K-$95K (Glassdoor est.)
320       0                  0                $83K-$133K (Glassdoor est.)
322       0                  0               $105K-$198K (Glassdoor est.)
323       0                  0                 $31K-$72K (Glassdoor est.)
324       0                  0                $98K-$182K (Glassdoor est.)
325       0                  0                $55K-$100K (Glassdoor est.)
326       0                  0                 $45K-$82K (Glassdoor est.)
328       0                  0                $83K-$135K (Glassdoor est.)
330       0                  0                $70K-$122K (Glassdoor est.)
331       0                  1       Employer Provided Salary:$200K-$250K
332       0                  0                $70K-$132K (Glassdoor est.)
333       0                  0                $73K-$124K (Glassdoor est.)

In [64]:
# print(minus_Kd.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary:','')).to_string())

min_max=minus_Kd.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary:',''))

In [78]:
#create new columns with minimum and maximum range of a salary
df['min_salary']=min_max.apply(lambda x: int(x.split('-')[0]))
df['max_salary']=min_max.apply(lambda x: int(x.split('-')[1]))

<ipython-input-78-3988422da235>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['min_salary']=min_max.apply(lambda x: int(x.split('-')[0]))
<ipython-input-78-3988422da235>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_salary']=min_max.apply(lambda x: int(x.split('-')[1]))

In [79]:
df.head()
df['min_salary'].dtype

dtype('int64')

In [84]:
df['avg_salary']=(df['min_salary']+df['max_salary'])/2

<ipython-input-84-d35e73ceeb84>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['avg_salary']=(df['min_salary']+df['max_salary'])/2

In [89]:
df[['min_salary','max_salary','avg_salary']].describe()

       min_salary  max_salary  avg_salary
count  742.000000  742.000000  742.000000
mean    74.068733  127.183288  100.626011
std     31.869282   46.909006   38.855948
min     10.000000   16.000000   13.500000
25%     52.000000   96.000000   73.500000
50%     69.500000  124.000000   97.500000
75%     91.000000  155.000000  122.500000
max    202.000000  306.000000  254.000000

In [94]:
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5

## Cleaning Company Name

In [95]:
print(df[['Company Name','Rating']].to_string())

                                                 Company Name  Rating
0                                      Tecolote Research\n3.8     3.8
1                  University of Maryland Medical System\n3.4     3.4
2                                                KnowBe4\n4.8     4.8
3                                                   PNNL\n3.8     3.8
4                                     Affinity Solutions\n2.9     2.9
5                                               CyrusOne\n3.4     3.4
6                                     ClearOne Advantage\n4.1     4.1
7                                             Logic20/20\n3.8     3.8
8                              Rochester Regional Health\n3.3     3.3
9                                               <intent>\n4.6     4.6
10                                                  Wish\n3.5     3.5
11                                               ManTech\n4.1     4.1
12                                               Walmart\n3.2     3.2
13                                                Yesler\n4.1     4.1
14                                Takeda Pharmaceuticals\n3.7     3.7
15                                               Audible\n3.6     3.6
16                                   Blueprint Medicines\n3.9     3.9
17                                                h2o.ai\n4.3     4.3
18                                                  Nuna\n4.2     4.2
19                                    Pinnacol Assurance\n4.0     4.0
20                                                 Porch\n3.2     3.2
21                                             Health IQ\n3.9     3.9
22                                         Truckstop.com\n3.8     3.8
23                                                 SMC 3\n4.3     4.3
25                                               Novetta\n4.0     4.0
26                                                Pfizer\n4.0     4.0
27                       First Tech Federal Credit Union\n3.5     3.5
28                           The Hanover Insurance Group\n3.7     3.7
29                                                Pfizer\n4.0     4.0
30                                               KnowBe4\n4.8     4.8
31                                                  PNNL\n3.8     3.8
32                                                Amrock\n3.6     3.6
33                                              Novartis\n3.8     3.8
34                                      Juniper Networks\n3.8     3.8
35                                   New England Biolabs\n4.7     4.7
36                                      Clarity Insights\n4.2     4.2
37                                                  Esri\n3.5     3.5
38                         Systems & Technology Research\n4.7     4.7
39                                             Sartorius\n3.5     3.5
40                                      Lancer Insurance\n3.5     3.5
41                                            Sauce Labs\n4.2     4.2
43                                              Persivia\n3.6     3.6
44                                                  Nuna\n4.2     4.2
45                                Edgewell Personal Care\n3.4     3.4
46                                    Equity Residential\n4.3     4.3
48                                          BPA Services\n5.0     5.0
49                                             Visa Inc.\n3.7     3.7
50                                               Intrado\n3.1     3.1
51                                              Centauri\n4.7     4.7
52                                           Caterpillar\n3.7     3.7
54                                 Zimmerman Advertising\n3.8     3.8
55                              Liberty Mutual Insurance\n3.3     3.3
56                              Torch Technologies, Inc.\n4.6     4.6
57                                              Swiss Re\n3.7     3.7
58                                      Northrop Grumman\n3.7     3.7
59                                             Sartorius\n3.5     3.5
60                                              Netskope\n4.1     4.1
61                                              1904labs\n4.7     4.7
62                                    ClearOne Advantage\n4.1     4.1
63                                              CyrusOne\n3.4     3.4
65                           The David J. Joseph Company\n4.4     4.4
66                                              USEReady\n4.3     4.3
67                                              Bill.com\n3.8     3.8
68                 Pacific Northwest National Laboratory\n3.8     3.8
70                     DICK'S Sporting Goods - Corporate\n3.8     3.8
72                                           Berg Health\n2.8     2.8
73                                     Oversight Systems\n4.7     4.7
75                                               C Space\n3.1     3.1
76                                          Numeric, LLC\n3.2     3.2
77                                               HP Inc.\n4.0     4.0
78                                              SpringML\n4.4     4.4
79                                              Grainger\n3.6     3.6
80                                      EAG Laboratories\n2.7     2.7
81                                     The Buffalo Group\n3.9     3.9
82                                              Carmeuse\n3.1     3.1
83                                               HP Inc.\n4.0     4.0
84                                                h2o.ai\n4.3     4.3
85                                        GNS Healthcare\n1.9     1.9
86                                               Peraton\n3.3     3.3
87                                               Pactera\n4.4     4.4
88                                                  Nurx\n3.9     3.9
89                                             webfx.com\n4.7     4.7
90   Johns Hopkins University Applied Physics Laboratory\n4.5     4.5
91                                       Productive Edge\n4.3     4.3
92                                    Excella Consulting\n4.0     4.0
93                                                Gensco\n4.4     4.4
94                                               Walmart\n3.2     3.2
95                                            Logic20/20\n3.8     3.8
96                                                 goTRG\n4.2     4.2
97                                        NMR Consulting\n4.5     4.5
99                                                iSeatz\n3.5     3.5
101                                  Nektar Therapeutics\n3.5     3.5
102                                           TransUnion\n3.9     3.9
104                                          IT Concepts\n4.7     4.7
105                      Scientific Research Corporation\n4.2     4.2
106              General Dynamics Information Technology\n3.4     3.4
107                                                MITRE\n3.2     3.2
108                                    The Buffalo Group\n3.9     3.9
109                                           DentaQuest\n3.1     3.1
110                                              Redjack\n4.1     4.1
112                                           7Park Data\n3.8     3.8
113                            Rapid Response Monitoring\n4.7     4.7
116                                           Trilogy Ed\n4.3     4.3
117                                               Gallup\n4.2     4.2
118                                              CapTech\n3.9     3.9
119                        American Axle & Manufacturing\n3.3     3.3
120                                         CentralReach\n4.7     4.7
122                                            Integrate\n4.3     4.3
123                                   Boys Town Hospital\n2.9     2.9
124                                           Demandbase\n4.5     4.5
125                                     Sapphire Digital\n3.4     3.4
126                               Takeda Pharmaceuticals\n3.7     3.7
127                                             <intent>\n4.6     4.6
128                                            Formation\n3.2     3.2
129                                             Autodesk\n4.0     4.0
130                                       Beck's Hybrids\n4.6     4.6
131                                              DrFirst\n2.8     2.8
132                                      Object Partners\n4.7     4.7
136                                L.A. Care Health Plan\n3.0     3.0
137                                         Red Ventures\n3.2     3.2
138                                           Quick Base\n4.4     4.4
139                             The E.W. Scripps Company\n3.5     3.5
140                               Upside Business Travel\n4.0     4.0
141                                   Equity Residential\n4.3     4.3
142                                              Synagro\n2.3     2.3
143                              Alliance Source Testing\n4.0     4.0
145                               Accuride International\n3.6     3.6
146                             Full Potential Solutions\n3.8     3.8
147                                            Visa Inc.\n3.7     3.7
148                                  Maven Wave Partners\n4.4     4.4
150                                              Novetta\n4.0     4.0
152               First Command Financial Services, Inc.\n3.2     3.2
153                                           Pharmavite\n2.9     2.9
154                              BioMarin Pharmaceutical\n3.8     3.8
156                                      Stratagem Group\n4.3     4.3
157                                        PA Consulting\n3.4     3.4
158                                              ManTech\n4.1     4.1
159                                               h2o.ai\n4.3     4.3
161                                          Gridiron IT\n5.0     5.0
162                                      Productive Edge\n4.3     4.3
164                               Evolve Vacation Rental\n3.7     3.7
166      The Church of Jesus Christ of Latter-day Saints\n4.2     4.2
167                         Maximus Real Estate Partners\n4.3     4.3
168                       Software Engineering Institute\n2.6     2.6
169                                                 PNNL\n3.8     3.8
170                                              AVANADE\n3.9     3.9
171                                               h2o.ai\n4.3     4.3
172                                         PatientPoint\n3.8     3.8
174                    BlueCross BlueShield of Tennessee\n3.8     3.8
175                                                 PNNL\n3.8     3.8
177                                              KnowBe4\n4.8     4.8
178                                       KSM Consulting\n4.4     4.4
179                                            Cogo Labs\n3.9     3.9
180                                      Church & Dwight\n3.4     3.4
181                                           MassMutual\n3.6     3.6
182                                            Genentech\n3.9     3.9
183                                     Juniper Networks\n3.8     3.8
185                               Takeda Pharmaceuticals\n3.7     3.7
187                              Legal & General America\n3.8     3.8
188                                      Western Digital\n3.5     3.5
190                                            Health IQ\n3.9     3.9
191                                                 Nuna\n4.2     4.2
192      The Church of Jesus Christ of Latter-day Saints\n4.2     4.2
193                                             Sunovion\n3.5     3.5
194                       National Student Clearinghouse\n2.9     2.9
197                                         Tower Health\n3.6     3.6
198                  State of Wisconsin Investment Board\n2.7     2.7
199                                  Rubius Therapeutics\n4.4     4.4
200                                             Autodesk\n4.0     4.0
201                                           OneMagnify\n4.3     4.3
202                                                 IZEA\n4.2     4.2
203                                         Vionic Group\n3.6     3.6
204                               Takeda Pharmaceuticals\n3.7     3.7
205                               Dodge Data & Analytics\n2.8     2.8
206                               Takeda Pharmaceuticals\n3.7     3.7
207                              Plymouth Rock Assurance\n3.3     3.3
208                                         CA-One Tech Cloud    -1.0
209                                     Beebe Healthcare\n3.6     3.6
210                               Takeda Pharmaceuticals\n3.7     3.7
211                                        Argo Group US\n3.4     3.4
212                      Associated Electric Cooperative\n4.1     4.1
213                       Software Engineering Institute\n2.6     2.6
215                                             PennyMac\n3.2     3.2
216                                              Zest AI\n3.9     3.9
217                       DECISIVE ANALYTICS Corporation\n4.7     4.7
221                          The Hanover Insurance Group\n3.7     3.7
223                         Karyopharm Therapeutics Inc.\n2.9     2.9
224                                          Tempus Labs\n3.0     3.0
225                            Recursion Pharmaceuticals\n4.7     4.7
226                                  P2 Energy Solutions\n3.7     3.7
228                            Rochester Regional Health\n3.3     3.3
229                                            ClearEdge\n4.0     4.0
230                                  Rubius Therapeutics\n4.4     4.4
233                                               Tapjoy\n3.9     3.9
234                            Rochester Regional Health\n3.3     3.3
235                                        Credit Sesame\n4.1     4.1
239                                    San Manuel Casino\n3.6     3.6
240                        Texas Health Huguley Hospital\n4.0     4.0
242                                 Teasdale Latin Foods\n2.4     2.4
243                       Software Engineering Institute\n2.6     2.6
245               Central California Alliance for Health\n3.5     3.5
246                    Pilot Flying J Travel Centers LLC\n3.0     3.0
247                                     Beebe Healthcare\n3.6     3.6
248                                      Palermo's Pizza\n3.3     3.3
250                     Advanced BioScience Laboratories\n2.7     2.7
251                                Echo Global Logistics\n3.4     3.4
253                                        Truckstop.com\n3.8     3.8
254                                      Lockheed Martin\n3.7     3.7
255                                     Acuity Insurance\n4.8     4.8
256                                           Fareportal\n3.8     3.8
257     Veterans Affairs, Veterans Health Administration\n3.4     3.4
258                                              Credera\n4.3     4.3
259                                              KnowBe4\n4.8     4.8
260                                      Church & Dwight\n3.4     3.4
262                                            Cogo Labs\n3.9     3.9
263               Spectrum Communications and Consulting\n3.4     3.4
264                                               NCSOFT\n3.1     3.1
265                                                MITRE\n3.2     3.2
266                           Dayton Freight Lines, Inc.\n4.3     4.3
267                                           MassMutual\n3.6     3.6
268                                            Genentech\n3.9     3.9
269                                     Juniper Networks\n3.8     3.8
270      Community Action Partnership of San Luis Obispo\n2.8     2.8
273                               Takeda Pharmaceuticals\n3.7     3.7
274                                           TrueAccord\n3.4     3.4
275                                          DRB Systems\n4.0     4.0
276                                      Western Digital\n3.5     3.5
277                              Legal & General America\n3.8     3.8
278                                           Corcentric\n3.7     3.7
281                                              U.Group\n3.5     3.5
282      The Church of Jesus Christ of Latter-day Saints\n4.2     4.2
284                                               Pfizer\n4.0     4.0
285                                                SMC 3\n4.3     4.3
288                               Systems Evolution Inc.\n4.7     4.7
289                                             Sunovion\n3.5     3.5
290                                           Eventbrite\n4.4     4.4
291                                               Centro\n4.1     4.1
292                       National Student Clearinghouse\n2.9     2.9
293                                             comScore\n2.5     2.5
295                                       SullivanCotter\n4.2     4.2
296                                                  NPD\n3.9     3.9
299                                        Bakery Agency\n4.3     4.3
300                  State of Wisconsin Investment Board\n2.7     2.7
302                                            Genentech\n3.9     3.9
305             Blue Cross & Blue Shield of Rhode Island\n3.4     3.4
306                                            Boys Town\n3.8     3.8
307                                         Tower Health\n3.6     3.6
308                           The HSC Health Care System\n3.3     3.3
309                                       Pro-Sphere Tek\n3.4     3.4
310                         Ameritas Life Insurance Corp\n3.0     3.0
311                                             Autodesk\n4.0     4.0
312                                             Genworth\n3.7     3.7
313                                  Rubius Therapeutics\n4.4     4.4
314                                           OneMagnify\n4.3     4.3
316                                               Pfizer\n4.0     4.0
317                                              Novetta\n4.0     4.0
318                                         Numeric, LLC\n3.2     3.2
319                                                 IZEA\n4.2     4.2
320                                           Trace Data\n3.9     3.9
322                               Takeda Pharmaceuticals\n3.7     3.7
323                                         Vionic Group\n3.6     3.6
324                               Takeda Pharmaceuticals\n3.7     3.7
325                               Dodge Data & Analytics\n2.8     2.8
326                                 Clearwater Analytics\n4.2     4.2
328                                     Tekvalley, Corp.\n4.0     4.0
330                                     BWX Technologies\n3.5     3.5
331                                         CA-One Tech Cloud    -1.0
332                                             PennyMac\n3.2     3.2
333                              Plymouth Rock Assurance\n3.3     3.3
334                                              Vermeer\n3.9     3.9
335                               Takeda Pharmaceuticals\n3.7     3.7
337                                     Beebe Healthcare\n3.6     3.6
339                                        Argo Group US\n3.4     3.4
341                                         L&T Infotech\n3.5     3.5
342                                 OceanFirst Financial\n4.3     4.3
344                      Associated Electric Cooperative\n4.1     4.1
346                       Software Engineering Institute\n2.6     2.6
347                                            Sotheby's\n3.6     3.6
348                      First Tech Federal Credit Union\n3.5     3.5
349                                               Amrock\n3.6     3.6
350                                Vanda Pharmaceuticals\n2.3     2.3
351                                              Zest AI\n3.9     3.9
352                                              Novetta\n4.0     4.0
353                                     CK-12 Foundation\n4.1     4.1

In [100]:
df[df['Rating']<0]

# print(df.apply(lambda x: x['Company Name'] if x['Rating']<0 else x['Company Name'][:-3],axis=1).to_string())

df['company_txt']=df.apply(lambda x: x['Company Name'] if x['Rating']<0 else x['Company Name'][:-3],axis=1)

<ipython-input-100-ece2a0a454d9>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['company_txt']=df.apply(lambda x: x['Company Name'] if x['Rating']<0 else x['Company Name'][:-3],axis=1)

In [101]:
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary,company_txt
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research\n
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System\n
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4\n
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL\n
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions\n

## Cleaning Location

In [130]:
df['state']=df['Location'].apply(lambda x: x.split(',')[-1])

<ipython-input-130-9a927b4e8b76>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['state']=df['Location'].apply(lambda x: x.split(',')[-1])

In [131]:
df.state.value_counts()

 CA    152
 MA    103
 NY     72
 VA     41
 IL     40
 MD     35
 PA     33
 TX     28
 NC     21
 WA     21
 NJ     17
 FL     16
 OH     14
 TN     13
 DC     11
 CO     11
 IN     10
 UT     10
 WI     10
 AZ      9
 MO      9
 AL      8
 GA      6
 MI      6
 KY      6
 DE      6
 CT      5
 IA      5
 NE      4
 LA      4
 OR      4
 KS      3
 NM      3
 MN      2
 ID      2
 RI      1
 SC      1
Name: state, dtype: int64

In [132]:
df.head()

# need to check if the job location is at the head quarter

print(df['Headquarters'].apply(lambda x: x.split(',')[-1] ).to_string())

0                   CA
1                   MD
2                   FL
3                   WA
4                   NY
5                   TX
6                   MD
7                   WA
8                   NY
9                   NY
10                  CA
11                  VA
12                  AR
13                  WA
14               Japan
15                  NJ
16                  MA
17                  CA
18                  CA
19                  CO
20                  WA
21                  CA
22                  ID
23                  GA
25                  VA
26                  NY
27                  CA
28                  MA
29                  NY
30                  FL
31                  WA
32                  MI
33         Switzerland
34                  CA
35                  MA
36                  IL
37                  CA
38                  MA
39             Germany
40                  NY
41                  CA
43                  MA
44                  CA
45                  CT
46                  IL
48                  VA
49                  CA
50                  NE
51                  VA
52                  IL
54                  FL
55                  MA
56                  AL
57         Switzerland
58                  VA
59             Germany
60                  CA
61                  MO
62                  MD
63                  TX
65                  OH
66                  NY
67                  CA
68                  WA
70                  PA
72                  MA
73                  GA
75                  MA
76                  PA
77                  CA
78                  CA
79                  IL
80                  CA
81                  VA
82             Belgium
83                  CA
84                  CA
85                  MA
86                  VA
87               China
88                  CA
89                  PA
90                  MD
91                  IL
92                  VA
93                  WA
94                  AR
95                  WA
96                  FL
97                  VA
99                  LA
101                 CA
102                 IL
104                 VA
105                 GA
106                 VA
107                 MA
108                 VA
109                 MA
110                 MD
112                 NY
113                 NY
116                 NY
117                 DC
118                 VA
119                 MI
120                 FL
122                 AZ
123                 NE
124                 CA
125                 NJ
126              Japan
127                 NY
128                 CA
129                 CA
130                 IN
131                 MD
132                 MN
136                 CA
137                 SC
138                 MA
139                 OH
140                 DC
141                 IL
142                 MD
143                 AL
145                 CA
146                 MO
147                 CA
148                 IL
150                 VA
152                 TX
153                 CA
154                 CA
156                 CO
157     United Kingdom
158                 VA
159                 CA
161                 VA
162                 IL
164                 CO
166                 UT
167                 CA
168                 PA
169                 WA
170                 WA
171                 CA
172                 OH
174                 TN
175                 WA
177                 FL
178                 IN
179                 MA
180                 NJ
181                 MA
182                 CA
183                 CA
185              Japan
187                 MD
188                 CA
190                 CA
191                 CA
192                 UT
193                 MA
194                 VA
197                 PA
198                 WI
199                 MA
200                 CA
201                 MI
202                 FL
203                 CA
204              Japan
205                 NJ
206              Japan
207                 MA
208                 CA
209                 DE
210              Japan
211            Bermuda
212                 MO
213                 PA
215                 CA
216                 CA
217                 VA
221                 MA
223                 MA
224                 IL
225                 UT
226                 CO
228                 NY
229                 MD
230                 MA
233                 CA
234                 NY
235                 CA
239                 CA
240                 TX
242                 TX
243                 PA
245                 CA
246                 TN
247                 DE
248                 WI
250                 MD
251                 IL
253                 ID
254                 MD
255                 WI
256                 NY
257                 DC
258                 TX
259                 FL
260                 NJ
262                 MA
263                 IL
264        South Korea
265                 MA
266                 OH
267                 MA
268                 CA
269                 CA
270                 CA
273              Japan
274                 CA
275                 OH
276                 CA
277                 MD
278                 NJ
281                 VA
282                 UT
284                 NY
285                 GA
288                 OH
289                 MA
290                 CA
291                 IL
292                 VA
293                 VA
295                 IL
296                 NY
299                 TX
300                 WI
302                 CA
305                 RI
306                 NE
307                 PA
308                 DC
309                 VA
310                 NE
311                 CA
312                 VA
313                 MA
314                 MI
316                 NY
317                 VA
318                 PA
319                 FL
320                 CA
322              Japan
323                 CA
324              Japan
325                 NJ
326                 ID
328                 CA
330                 VA
331                 CA
332                 CA
333                 MA
334                 IA
335              Japan
337                 DE
339            Bermuda
341              India
342                 NJ
344                 MO
346                 PA
347                 NY
348                 CA
349                 MI
350                 DC
351                 CA
352                 VA
353                 CA
354                 CA
355                 VA
356                 MA
357                 VA
358        Switzerland
362              Japan
364                 NC
366                 MA
367                 CA
368                 MA
369                 IL
370                 VA
371                 VA
372        Switzerland
375                 CA
376                 TX
377                 CA
379                 CA
380        Switzerland
381                 CA
382                 CO
383                 MA
384                 VA
386                 CO
387                 WA
388                 MA
390                 UT
391                 CA
392                 NY
394                 MA
396                 CA
397                 FL
398                 MD
399                 CA
400                 CA
401                 DC
403                 NC
406                 NY
407                 PA
409                 NY
410                 VA
411                 MA
412                 CA
413                 MA
414                 CA
415                 IL
416                 CA
417                 NC
419                 MA
420              India
421                 CA
425                 CA
426                 MA
427                 TX
428                 IL
429                 TX
430                 NY
431                 CA
433              Japan
434                 PA
435                 IL
437                 CO
442                 CA
443                 TN
444                 CA
446     United Kingdom
447                 CO
448                 WI
449                 MA
450                 VA
452                 MA
454                 CA
455                 MD
456                 DE
458                 NC
459                 OH
461                 IN
462                 IL
463                 MA
464                 MA
466                 NC
467                 CA
468                 CA
469                 NC
470                 NC
471                 MA
472                 CA
473                 PA
476                 FL
477                 VA
479                 MA
482                 NY
483                 WI
485                 CA
486                 NY
487                 CA
488                 NY
489                 MA
490                 CA
491              Spain
492                 TN
493                 DC
494                 FL
495                 FL
496                 MO
497                 TX
498     United Kingdom
499                 MA
500                 MD
501                 NC
502                 IL
505                 CA
506                 CA
507                 NY
508                 IL
509                 IL
510                 IA
512                 WA
516                 IA
517                 MA
518                 CA
519                 PA
520                 CA
521                 WA
522                 CO
523                 GA
524                 MA
525                 TX
526                 TX
528                 NC
530                 MA
532                 NC
533                 NJ
534                 PA
535                 CA
537                 CA
538                 NY
539                 NC
540            Germany
541                 MO
542                 VA
543                 MA
544                 WA
545                 UT
546                 NY
548                 CA
549                 CA
550                 CA
552                 NY
554                 TN
555                 CA
556                 CA
557                 NY
558                 CA
560                 PA
561                 MA
562                 CA
563                 MD
565                 FL
566                 CA
567                 DC
568                 CA
570                 CA
572                 MA
573                 CA
575                 NJ
576                 NC
577                 CA
578                 MD
579                 VA
580                 CA
582     United Kingdom
583              India
585                 NY
586                 MI
587                 NJ
588                 NY
589                 MA
590             France
591                 NY
594                 PA
595                 TN
597                 NY
599                 NY
600                 VA
601                 CA
602                 MA
603                 CA
604                 VA
605                 CA
606                 NY
607                 IL
608                 CA
609                 NY
610                 NC
613              India
614                 MA
616                 NY
617                 CA
619                 NY
622                 VA
623     United Kingdom
624                 VA
625                 CA
627                 MA
629                 IL
630                 CA
631                 CA
632                 TX
633                 TX
634                 VA
635                 CA
636                 NY
637                 MA
638     United Kingdom
639                 MA
640                 NY
642                 CA
643                 NY
644              Japan
645                 PA
646                 CT
647                 IL
648                 CA
651                 NY
652                 CO
653                 IL
654                 UT
655        South Korea
658     United Kingdom
660                 CA
661                 CA
662                 NY
663                 CA
664                 CA
665     United Kingdom
666                 TN
668        Switzerland
669            Germany
670                 CO
671                 WI
672                 IN
673                 VA
674                 MA
675                 MA
676                 NY
678        Switzerland
679                 CA
681                 MD
682                 DE
683                 NC
685                 OH
687                 MA
688                 IN
689                 FL
690                 NY
691                 IL
692                 MA
694                 MA
695                 NC
696                 CA
697                 NC
698                 CA
699                 NC
700                 GA
701                 CA
702                 MA
703                 CA
704                 CA
705                 NC
706                 MA
707     United Kingdom
708                 CA
709                 PA
711                 VA
712                 PA
714                 UT
715                 MA
718                 UT
719                 AL
721                 WI
722                 NY
723                 NY
725                 VA
726                 NY
727                 VA
728                 CA
730                 MA
731                 MA
732        Switzerland
733                 NY
734                 PA
735                 CA
736                 TN
737        Switzerland
738                 CA
740              Spain
741                 -1
742                 FL
743                 DC
744                 AZ
745                 CA
746                 MO
747                 VA
748                 FL
749     United Kingdom
750                 TX
751                 MD
752                 IL
753                 IL
754                 MA
755                 CA
756                 NC
757                 OR
758                 CO
759                 CA
761                 CA
763                 CA
766                 NY
767                 IA
768                 CA
769                 WA
773                 IA
776                 MA
777                 NY
778                 CA
779                 PA
780                 CA
781                 CA
782                 CA
783                 WA
784                 IL
785                 MA
786                 CO
787                 GA
788                 NY
789                 TX
790                 TX
791                 NC
794                 MA
795                 NC
797                 PA
799     United Kingdom
802                 NJ
803                 VA
804                 PA
806                 CA
807                 CA
808                 NY
809                 MA
810                 NY
811                 CA
812                 NC
815                 MA
816                 PA
817                 WA
818                 MD
819                 CA
820                 PA
821                 CA
822                 MD
823                 MA
824                 MA
825                 MA
826                 MA
827                 CA
828                 CA
829                 WA
830              India
831     United Kingdom
832                 NY
836                 CA
837                 NJ
838                 NY
839                 UT
840                 VA
841                 VA
845                 CA
848                 MA
851                 CA
852                 IL
853                 CA
854                 TX
855                 VA
856                 TX
857                 CA
858     United Kingdom
859                 MA
860                 OH
861                 VA
863                 TX
864                 CA
866              Japan
867                 CT
868                 NY
869                 IL
870                 PA
871                 CA
875                 CO
877                 UT
878                 NY
879                 CA
880                 CA
881                 IL
883        South Korea
884             France
886     United Kingdom
887                 CA
892                 MA
893                 MI
895                 CA
896                 NY
897                 CA
898                 NY
899                 CA
900     United Kingdom
901                 CO
902                 TN
904     United Kingdom
907                 CO
909                 WI
910                 IN
911                 VA
912                 MA
913                 MA
914                 NY
916        Switzerland
919                 DE
920                 CA
921                 MD
924                 PA
926                 NC
928                 CA
929                 OH
930                 IN
931                 FL
932                 MA
933                 NY
934                 IL
935                 MA
936                 MA
938                 NC
939                 CA
940                 CA
941                 NC
942                 NC
943                 CA
944                 MA
945                 CA
946                 CA
947                 MA
948                 CA
949                 NC
950     United Kingdom
951                 CA
952                 PA
953                 PA
955                 VA

In [133]:
print(df[['Headquarters','Location']].to_string())

                   Headquarters                           Location
0                    Goleta, CA                    Albuquerque, NM
1                 Baltimore, MD                      Linthicum, MD
2                Clearwater, FL                     Clearwater, FL
3                  Richland, WA                       Richland, WA
4                  New York, NY                       New York, NY
5                    Dallas, TX                         Dallas, TX
6                 Baltimore, MD                      Baltimore, MD
7                   Seattle, WA                       San Jose, CA
8                 Rochester, NY                      Rochester, NY
9                  New York, NY                       New York, NY
10            San Francisco, CA                       San Jose, CA
11                  Herndon, VA                      Chantilly, VA
12              Bentonville, AR                          Plano, TX
13                  Seattle, WA                        Seattle, WA
14                 OSAKA, Japan                      Cambridge, MA
15                   Newark, NJ                         Newark, NJ
16                Cambridge, MA                      Cambridge, MA
17            Mountain View, CA                  Mountain View, CA
18            San Francisco, CA                  San Francisco, CA
19                   Denver, CO                         Denver, CO
20                  Seattle, WA                        Seattle, WA
21            Mountain View, CA                         Dallas, TX
22             New Plymouth, ID                        Chicago, IL
23           Peachtree City, GA                     Louisville, KY
25                  Mc Lean, VA                        Herndon, VA
26                 New York, NY                      Cambridge, MA
27                 San Jose, CA                      Hillsboro, OR
28                Worcester, MA                      Worcester, MA
29                 New York, NY                         Groton, CT
30               Clearwater, FL                     Clearwater, FL
31                 Richland, WA                       Richland, WA
32                  Detroit, MI                        Detroit, MI
33           Basel, Switzerland                      Cambridge, MA
34                Sunnyvale, CA                      Sunnyvale, CA
35                  Ipswich, MA                        Ipswich, MA
36                  Chicago, IL                       San Jose, CA
37                 Redlands, CA                       Redlands, CA
38                   Woburn, MA                         Woburn, MA
39           Gottingen, Germany                        Fremont, CA
40               Long Beach, NY                     Long Beach, NY
41            San Francisco, CA                  San Francisco, CA
43                   Lowell, MA                    Marlborough, MA
44            San Francisco, CA                  San Francisco, CA
45                  Shelton, CT                      Allendale, NJ
46                  Chicago, IL                        Chicago, IL
48               Alexandria, VA                     Washington, DC
49              Foster City, CA                       Bellevue, WA
50                    Omaha, NE                       Longmont, CO
51                Chantilly, VA                    Beavercreek, OH
52                Deerfield, IL                         Peoria, IL
54          Fort Lauderdale, FL                Fort Lauderdale, FL
55                   Boston, MA                         Boston, MA
56               Huntsville, AL                     Huntsville, AL
57          Zurich, Switzerland                         Armonk, NY
58             Falls Church, VA                      San Diego, CA
59           Gottingen, Germany                    Albuquerque, NM
60              Santa Clara, CA                  San Francisco, CA
61              Saint Louis, MO                    Saint Louis, MO
62                Baltimore, MD                      Baltimore, MD
63                   Dallas, TX                         Dallas, TX
65               Cincinnati, OH                     Cincinnati, OH
66                 New York, NY                       New York, NY
67                Palo Alto, CA                      Palo Alto, CA
68                 Richland, WA                       Richland, WA
70               Coraopolis, PA                     Coraopolis, PA
72               Framingham, MA                     Framingham, MA
73                  Atlanta, GA                        Atlanta, GA
75                   Boston, MA                         Boston, MA
76              Chadds Ford, PA                   Philadelphia, PA
77                Palo Alto, CA                      Vancouver, WA
78               Pleasanton, CA                   Indianapolis, IN
79              Lake Forest, IL                    Lake Forest, IL
80                San Diego, CA               Maryland Heights, MO
81                   Reston, VA                Charlottesville, VA
82    Louvain-la-Neuve, Belgium                     Pittsburgh, PA
83                Palo Alto, CA                      Vancouver, WA
84            Mountain View, CA                  Mountain View, CA
85                Cambridge, MA                      Cambridge, MA
86                  Herndon, VA                      Chantilly, VA
87               Beijing, China                       San Jose, CA
88            San Francisco, CA                  San Francisco, CA
89               Harrisburg, PA                     Harrisburg, PA
90                   Laurel, MD                         Laurel, MD
91                  Chicago, IL                        Chicago, IL
92                Arlington, VA                      Arlington, VA
93                   Tacoma, WA                         Tacoma, WA
94              Bentonville, AR                          Plano, TX
95                  Seattle, WA                       San Jose, CA
96                    Miami, FL                          Miami, FL
97                Chantilly, VA                     Huntsville, AL
99              New Orleans, LA                    New Orleans, LA
101           San Francisco, CA                  San Francisco, CA
102                 Chicago, IL                        Atlanta, GA
104                  Vienna, VA                       Landover, MD
105                 Atlanta, GA                 Patuxent River, MD
106                 Fairfax, VA                       Suitland, MD
107                 Bedford, MA                         McLean, VA
108                  Reston, VA                   Fort Belvoir, VA
109                  Boston, MA                      Milwaukee, WI
110           Silver Spring, MD                  Silver Spring, MD
112                New York, NY                       New York, NY
113                Syracuse, NY                       Syracuse, NY
116                New York, NY                        Houston, TX
117              Washington, DC                     Washington, DC
118                Richmond, VA                      Charlotte, NC
119                 Detroit, MI                     Southfield, MI
120           Pompano Beach, FL                        Matawan, NJ
122                 Phoenix, AZ                        Phoenix, AZ
123                   Omaha, NE                          Omaha, NE
124           San Francisco, CA                  San Francisco, CA
125               Lyndhurst, NJ                      Lyndhurst, NJ
126                OSAKA, Japan                      Cambridge, MA
127                New York, NY                       New York, NY
128           San Francisco, CA                  San Francisco, CA
129              San Rafael, CA                  San Francisco, CA
130                 Atlanta, IN                        Atlanta, IN
131               Rockville, MD                      Rockville, MD
132             Minneapolis, MN                    Minneapolis, MN
136             Los Angeles, CA                    Los Angeles, CA
137               Fort Mill, SC                      Charlotte, NC
138               Cambridge, MA                      Cambridge, MA
139              Cincinnati, OH                     Cincinnati, OH
140              Washington, DC                     Washington, DC
141                 Chicago, IL                        Chicago, IL
142               Baltimore, MD                      Baltimore, MD
143                 Decatur, AL                      Alabaster, AL
145        Santa Fe Springs, CA  Santa Fe Springs, Los Angeles, CA
146             Kansas City, MO                    Kansas City, MO
147             Foster City, CA                        Ashburn, VA
148                 Chicago, IL                        Chicago, IL
150                 Mc Lean, VA                        Herndon, VA
152              Fort Worth, TX                     Fort Worth, TX
153              West Hills, CA                       Valencia, CA
154              San Rafael, CA                         Novato, CA
156                  Aurora, CO                         Aurora, CO
157      London, United Kingdom                       New York, NY
158                 Herndon, VA                      Chantilly, VA
159           Mountain View, CA                  Mountain View, CA
161                  Reston, VA                          Tampa, FL
162                 Chicago, IL                        Chicago, IL
164                  Denver, CO                         Denver, CO
166          Salt Lake City, UT                       Riverton, UT
167           San Francisco, CA                  San Francisco, CA
168              Pittsburgh, PA                     Pittsburgh, PA
169                Richland, WA                       Richland, WA
170                 Seattle, WA                     Washington, DC
171           Mountain View, CA                        Chicago, IL
172              Cincinnati, OH                     Cincinnati, OH
174             Chattanooga, TN                    Chattanooga, TN
175                Richland, WA                       Richland, WA
177              Clearwater, FL                     Clearwater, FL
178            Indianapolis, IN                   Indianapolis, IN
179               Cambridge, MA                      Cambridge, MA
180                   Ewing, NJ                          Ewing, NJ
181             Springfield, MA                         Boston, MA
182     South San Francisco, CA            South San Francisco, CA
183               Sunnyvale, CA                      Cupertino, CA
185                OSAKA, Japan                         Boston, MA
187               Frederick, MD                      Frederick, MD
188                San Jose, CA                       San Jose, CA
190           Mountain View, CA                         Dallas, TX
191           San Francisco, CA                  San Francisco, CA
192          Salt Lake City, UT                       Riverton, UT
193             Marlborough, MA                    Marlborough, MA
194                 Herndon, VA                        Herndon, VA
197                 Reading, PA                   West Reading, PA
198                 Madison, WI                        Madison, WI
199               Cambridge, MA                      Cambridge, MA
200              San Rafael, CA                  San Francisco, CA
201                 Detroit, MI                       Dearborn, MI
202             Winter Park, FL                    Winter Park, FL
203              San Rafael, CA                     San Rafael, CA
204                OSAKA, Japan                      San Diego, CA
205                Hamilton, NJ                       Hamilton, NJ
206                OSAKA, Japan                         Boston, MA
207                  Boston, MA                     Woodbridge, NJ
208                 Fremont, CA                  San Francisco, CA
209                   Lewes, DE                          Lewes, DE
210                OSAKA, Japan                         Boston, MA
211           Hamilton, Bermuda                       New York, NY
212             Springfield, MO                    Springfield, MO
213              Pittsburgh, PA                     Pittsburgh, PA
215        Westlake Village, CA                        Phoenix, AZ
216                 Burbank, CA                        Burbank, CA
217               Arlington, VA                     Huntsville, AL
221               Worcester, MA                      Worcester, MA
223                  Newton, MA                         Newton, MA
224                 Chicago, IL                        Chicago, IL
225          Salt Lake City, UT                 Salt Lake City, UT
226                  Denver, CO                      Lafayette, LA
228               Rochester, NY                      Rochester, NY
229      Annapolis Junction, MD             Annapolis Junction, MD
230               Cambridge, MA                      Cambridge, MA
233           San Francisco, CA                  San Francisco, CA
234               Rochester, NY                      Rochester, NY
235           Mountain View, CA                  Mountain View, CA
239                Highland, CA                       Highland, CA
240               Arlington, TX                       Burleson, TX
242            Flower Mound, TX                      Hoopeston, IL
243              Pittsburgh, PA                     Pittsburgh, PA
245           Scotts Valley, CA                  Scotts Valley, CA
246               Knoxville, TN                      Knoxville, TN
247                   Lewes, DE                      Millville, DE
248               Milwaukee, WI                      Milwaukee, WI
250               Rockville, MD                      Rockville, MD
251                 Chicago, IL                        Chicago, IL
253            New Plymouth, ID                        Chicago, IL
254                Bethesda, MD                        Herndon, VA
255               Sheboygan, WI                      Sheboygan, WI
256                New York, NY                       New York, NY
257              Washington, DC                    New Orleans, LA
258                  Dallas, TX                         Dallas, TX
259              Clearwater, FL                     Clearwater, FL
260                   Ewing, NJ                          Ewing, NJ
262               Cambridge, MA                      Cambridge, MA
263                 Chicago, IL                        Chicago, IL
264          Seoul, South Korea                      San Mateo, CA
265                 Bedford, MA                         McLean, VA
266                  Dayton, OH                         Dayton, OH
267             Springfield, MA                         Boston, MA
268     South San Francisco, CA            South San Francisco, CA
269               Sunnyvale, CA                      Cupertino, CA
270         San Luis Obispo, CA                        Parlier, CA
273                OSAKA, Japan                         Boston, MA
274           San Francisco, CA                  San Francisco, CA
275                   Akron, OH                       Meridian, ID
276                San Jose, CA                       San Jose, CA
277               Frederick, MD                      Frederick, MD
278             Cherry Hill, NJ                    Cherry Hill, NJ
281               Arlington, VA                   Indianapolis, IN
282          Salt Lake City, UT                       Riverton, UT
284                New York, NY                      Cambridge, MA
285          Peachtree City, GA                     Louisville, KY
288              Cincinnati, OH                       New York, NY
289             Marlborough, MA                    Marlborough, MA
290           San Francisco, CA                      Nashville, TN
291                 Chicago, IL                        Chicago, IL
292                 Herndon, VA                        Herndon, VA
293                  Reston, VA                       Portland, OR
295                 Chicago, IL                    Minneapolis, MN
296         Port Washington, NY                Port Washington, NY
299                  Austin, TX                         Austin, TX
300                 Madison, WI                        Madison, WI
302     South San Francisco, CA            South San Francisco, CA
305              Providence, RI                     Providence, RI
306                   Omaha, NE                          Omaha, NE
307                 Reading, PA                   West Reading, PA
308              Washington, DC                     Washington, DC
309              Alexandria, VA                         Austin, TX
310                 Lincoln, NE                     Cincinnati, OH
311              San Rafael, CA                  San Francisco, CA
312                Richmond, VA                        Raleigh, NC
313               Cambridge, MA                      Cambridge, MA
314                 Detroit, MI                       Dearborn, MI
316                New York, NY                         Groton, CT
317                 Mc Lean, VA                        Herndon, VA
318             Chadds Ford, PA                          Phila, PA
319             Winter Park, FL                    Winter Park, FL
320               Santa Ana, CA                        Oakland, CA
322                OSAKA, Japan                      San Diego, CA
323              San Rafael, CA                     San Rafael, CA
324                OSAKA, Japan                         Boston, MA
325                Hamilton, NJ                       Hamilton, NJ
326                   Boise, ID                          Boise, ID
328              Pleasanton, CA                  San Francisco, CA
330               Lynchburg, VA                      Oak Ridge, TN
331                 Fremont, CA                  San Francisco, CA
332        Westlake Village, CA                   Agoura Hills, CA
333                  Boston, MA                     Woodbridge, NJ
334                   Pella, IA                          Pella, IA
335                OSAKA, Japan                         Boston, MA
337                   Lewes, DE                          Lewes, DE
339           Hamilton, Bermuda                       New York, NY
341               Mumbai, India                      San Ramon, CA
342              Toms River, NJ                       Red Bank, NJ
344             Springfield, MO                    Springfield, MO
346              Pittsburgh, PA                     Pittsburgh, PA
347                New York, NY                       New York, NY
348                San Jose, CA                      Hillsboro, OR
349                 Detroit, MI                        Detroit, MI
350              Washington, DC                     Washington, DC
351                 Burbank, CA                        Burbank, CA
352                 Mc Lean, VA                   Fort Belvoir, VA
353               Palo Alto, CA                      Palo Alto, CA
354        Westlake Village, CA                        Phoenix, AZ
355               Arlington, VA                     Huntsville, AL
356                 Waltham, MA                      San Diego, CA
357                  Reston, VA                        Houston, TX
358         Zurich, Switzerland                         Armonk, NY
362                OSAKA, Japan                      Cambridge, MA
364               Charlotte, NC                       Columbia, SC
366               Worcester, MA                      Worcester, MA
367     South San Francisco, CA            South San Francisco, CA
368             Springfield, MA                    Springfield, MA
369                 Chicago, IL                        Chicago, IL
370                 Fairfax, VA                     Washington, DC
371                 Herndon, VA                        Herndon, VA

In [136]:
df['same_state']=df.apply(lambda x: 1 if x['Headquarters']==x['Location'] else 0,axis=1)

<ipython-input-136-7e6160c786d3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['same_state']=df.apply(lambda x: 1 if x['Headquarters']==x['Location'] else 0,axis=1)

In [137]:
df.same_state.value_counts()

1    414
0    328
Name: same_state, dtype: int64

## Cleaning Age

In [146]:
df[df['Founded']<0]

df['age']=df['Founded'].apply(lambda x: x if x<0 else 2020-x)

<ipython-input-146-bb9eaef421e2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age']=df['Founded'].apply(lambda x: x if x<0 else 2020-x)

In [147]:
print(df[['age','Founded']].to_string())

     age  Founded
0     47     1973
1     36     1984
2     10     2010
3     55     1965
4     22     1998
5     20     2000
6     12     2008
7     15     2005
8      6     2014
9     11     2009
10     9     2011
11    52     1968
12    58     1962
13     8     2012
14   239     1781
15    25     1995
16     9     2011
17     9     2011
18    10     2010
19   105     1915
20     8     2012
21     7     2013
22    25     1995
23    85     1935
25     8     2012
26   171     1849
27    68     1952
28   168     1852
29   171     1849
30    10     2010
31    55     1965
32    23     1997
33    24     1996
34    24     1996
35    46     1974
36    12     2008
37    51     1969
38    10     2010
39   150     1870
40    35     1985
41    12     2008
43    -1       -1
44    10     2010
45     5     2015
46    27     1993
48    -1       -1
49    62     1958
50    34     1986
51    21     1999
52    95     1925
54    36     1984
55   108     1912
56    18     2002
57   157     1863
58    81     1939
59   150     1870
60     8     2012
61     4     2016
62    12     2008
63    20     2000
65   135     1885
66     9     2011
67    14     2006
68    55     1965
70    72     1948
72    14     2006
73    17     2003
75    21     1999
76    -1       -1
77    81     1939
78     5     2015
79    93     1927
80    42     1978
81    10     2010
82   160     1860
83    81     1939
84     9     2011
85    20     2000
86     3     2017
87    25     1995
88     4     2016
89    23     1997
90    78     1942
91    12     2008
92    18     2002
93    72     1948
94    58     1962
95    15     2005
96    12     2008
97    24     1996
99    21     1999
101   30     1990
102   52     1968
104   17     2003
105   32     1988
106   24     1996
107   62     1958
108   10     2010
109   19     2001
110   13     2007
112    8     2012
113   28     1992
116    5     2015
117   85     1935
118   23     1997
119   26     1994
120    8     2012
122   10     2010
123   43     1977
124   14     2006
125    1     2019
126  239     1781
127   11     2009
128    5     2015
129   38     1982
130   83     1937
131   20     2000
132   24     1996
136   23     1997
137   20     2000
138   21     1999
139  142     1878
140    5     2015
141   27     1993
142   34     1986
143   20     2000
145   54     1966
146    3     2017
147   62     1958
148   12     2008
150    8     2012
152   62     1958
153   49     1971
154   23     1997
156   13     2007
157   77     1943
158   52     1968
159    9     2011
161    3     2017
162   12     2008
164    9     2011
166   -1       -1
167    7     2013
168   36     1984
169   55     1965
170   20     2000
171    9     2011
172   33     1987
174   75     1945
175   55     1965
177   10     2010
178   12     2008
179   15     2005
180  174     1846
181  169     1851
182   44     1976
183   24     1996
185  239     1781
187   39     1981
188   50     1970
190    7     2013
191   10     2010
192   -1       -1
193   10     2010
194   27     1993
197    3     2017
198   69     1951
199    7     2013
200   38     1982
201   53     1967
202   14     2006
203   14     2006
204  239     1781
205    6     2014
206  239     1781
207   38     1982
208    3     2017
209   85     1935
210  239     1781
211   72     1948
212   59     1961
213   36     1984
215   12     2008
216   11     2009
217   24     1996
221  168     1852
223   -1       -1
224    5     2015
225    7     2013
226   -1       -1
228    6     2014
229   18     2002
230    7     2013
233   13     2007
234    6     2014
235   10     2010
239   34     1986
240   43     1977
242   -1       -1
243   36     1984
245   24     1996
246   62     1958
247   85     1935
248   56     1964
250   59     1961
251   15     2005
253   25     1995
254   25     1995
255   95     1925
256   18     2002
257   90     1930
258   21     1999
259   10     2010
260  174     1846
262   15     2005
263   28     1992
264   23     1997
265   62     1958
266   39     1981
267  169     1851
268   44     1976
269   24     1996
270   -1       -1
273  239     1781
274    7     2013
275   36     1984
276   50     1970
277   39     1981
278   24     1996
281    1     2019
282   -1       -1
284  171     1849
285   85     1935
288   28     1992
289   10     2010
290   14     2006
291   19     2001
292   27     1993
293   21     1999
295   28     1992
296   54     1966
299   10     2010
300   69     1951
302   44     1976
305   81     1939
306  103     1917
307    3     2017
308  137     1883
309   14     2006
310  133     1887
311   38     1982
312   16     2004
313    7     2013
314   53     1967
316  171     1849
317    8     2012
318   -1       -1
319   14     2006
320   20     2000
322  239     1781
323   14     2006
324  239     1781
325    6     2014
326   16     2004
328   -1       -1
330  170     1850
331    3     2017
332   12     2008
333   38     1982
334   72     1948
335  239     1781
337   85     1935
339   72     1948
341   23     1997
342  118     1902
344   59     1961
346   36     1984
347  276     1744
348   68     1952
349   23     1997
350   17     2003
351   11     2009
352    8     2012
353   13     2007
354   12     2008
355   24     1996
356   33     1987
357   38     1982
358  157     1863
362  239     1781
364   91     1929
366  168     1852
367   44     1976
368  169     1851
369    5     2015
370   24     1996
371   52     1968
372   24     1996
375   38     1982
376   73     1947
377   -1       -1
379    5     2015
380   24     1996
381   24     1996
382   27     1993
383   -1       -1
384   52     1968
386   -1       -1
387   55     1965
388  169     1851
390    7     2013
391   51     1969
392    6     2014
394    7     2013
396   12     2008
397   29     1991
398   18     2002
399    5     2015
400   10     2010
401   13     2007
403    3     2017
406   22     1998
407   83     1937
409    6     2014
410   31     1989
411  169     1851
412   51     1969
413   46     1974
414   13     2007
415   92     1928
416   10     2010
417  145     1875
419  169     1851
420   39     1981
421    7     2013
425   34     1986
426   10     2010
427   43     1977
428   47     1973
429   -1       -1
430   17     2003
431   -1       -1
433  239     1781
434   36     1984
435   12     2008
437   54     1966
442   24     1996
443   62     1958
444   10     2010
446  107     1913
447  105     1915
448   56     1964
449   36     1984
450   21     1999
452  108     1912
454    8     2012
455   59     1961
456   85     1935
458  145     1875
459   31     1989
461   24     1996
462   52     1968
463   62     1958
464   44     1976
466  145     1875
467   14     2006
468    9     2011
469    5     2015
470    5     2015
471   32     1988
472   -1       -1
473   36     1984
476   36     1984
477   -1       -1
479  169     1851
482  171     1849
483  150     1870
485   11     2009
486   18     2002
487   30     1990
488   10     2010
489  108     1912
490   48     1972
491  164     1856
492   39     1981
493   16     2004
494    8     2012
495   25     1995
496   18     2002
497   10     2010
498   77     1943
499   12     2008
500   59     1961
501  145     1875
502   15     2005
505   13     2007
506   51     1969
507   42     1978
508   95     1925
509   27     1993
510   -1       -1
512   55     1965
516   28     1992
517   17     2003
518   -1       -1
519   37     1983
520   14     2006
521   55     1965
522   24     1996
523   20     2000
524  108     1912
525   73     1947
526   -1       -1
528  145     1875
530   98     1922
532   62     1958
533   31     1989
534   17     2003
535   12     2008
537   13     2007
538   18     2002
539  145     1875
540  150     1870
541    4     2016
542    6     2014
543  169     1851
544   55     1965
545    7     2013
546  208     1812
548   21     1999
549    4     2016
550   51     1969
552    6     2014
554   13     2007
555   12     2008
556   10     2010
557   44     1976
558   28     1992
560   -1       -1
561    7     2013
562   12     2008
563   18     2002
565   29     1991
566   10     2010
567   13     2007
568    5     2015
570   32     1988
572   10     2010
573    8     2012
575   -1       -1
576    3     2017
577   -1       -1
578   -1       -1
579   51     1969
580   85     1935
582    4     2016
583   -1       -1
585   22     1998
586   -1       -1
587    9     2011
588   13     2007
589  135     1885
590   53     1967
591  106     1914
594   83     1937
595   -1       -1
597   21     1999
599    6     2014
600   31     1989
601   81     1939
602  169     1851
603   13     2007
604   81     1939
605   62     1958
606    6     2014
607   92     1928
608   10     2010
609   14     2006
610  145     1875
613   39     1981
614  169     1851
616   40     1980
617    7     2013
619    8     2012
622   66     1954
623  107     1913
624   14     2006
625    8     2012
627   10     2010
629   47     1973
630   34     1986
631   18     2002
632   43     1977
633   -1       -1
634   81     1939
635   23     1997
636   19     2001
637  108     1912
638  107     1913
639   62     1958
640   17     2003
642   -1       -1
643   13     2007
644  239     1781
645   36     1984
646    9     2011
647   12     2008
648   14     2006
651   15     2005
652   54     1966
653   12     2008
654   -1       -1
655   23     1997
658  190     1830
660   12     2008
661   32     1988
662   10     2010
663   24     1996
664   38     1982
665  107     1913
666   62     1958
668  157     1863
669  150     1870
670  105     1915
671   56     1964
672   16     2004
673   21     1999
674   36     1984
675  108     1912
676   45     1975
678   24     1996
679    8     2012
681   59     1961
682   85     1935
683  145     1875
685   31     1989
687  168     1852
688   24     1996
689   43     1977
690   18     2002
691   52     1968
692   62     1958
694   44     1976
695  145     1875
696   14     2006
697    5     2015
698    9     2011
699    5     2015
700   17     2003
701    6     2014
702   32     1988
703   -1       -1
704   12     2008
705    3     2017
706  169     1851
707  190     1830
708   14     2006
709   36     1984
711   53     1967
712   -1       -1
714   -1       -1
715  169     1851
718   43     1977
719    6     2014
721  150     1870
722  171     1849
723   18     2002
725    8     2012
726   10     2010
727    8     2012
728   30     1990
730  169     1851
731  108     1912
732   24     1996
733    9     2011
734   -1       -1
735   48     1972
736   39     1981
737   24     1996
738   14     2006
740  164     1856
741   -1       -1
742    8     2012
743   16     2004
744   18     2002
745   11     2009
746   18     2002
747    3     2017
748   25     1995
749   77     1943
750   10     2010
751   59     1961
752   95     1925
753   15     2005
754   12     2008
755   13     2007
756  145     1875
757   39     1981
758   -1       -1
759   48     1972
761   13     2007
763   51     1969
766   42     1978
767   -1       -1
768   26     1994
769   55     1965
773   28     1992
776   17     2003
777  171     1849
778   -1       -1
779   37     1983
780   26     1994
781   14     2006
782    9     2011
783   55     1965
784   25     1995
785  108     1912
786   24     1996
787   20     2000
788   47     1973
789   -1       -1
790   73     1947
791  145     1875
794   98     1922
795   62     1958
797   72     1948
799  107     1913
802   31     1989
803  121     1899
804   17     2003
806   12     2008
807   13     2007
808   12     2008
809   29     1991
810   18     2002
811   18     2002
812  145     1875
815   29     1991
816   36     1984
817   41     1979
818  131     1889
819   -1       -1
820   26     1994
821   50     1970
822   59     1961
823   12     2008
824   98     1922
825   12     2008
826  108     1912
827    9     2011
828   14     2006
829   55     1965
830   39     1981
831  107     1913
832   40     1980
836    7     2013
837   31     1989
838    8     2012
839   -1       -1
840   66     1954
841   14     2006
845    8     2012
848   10     2010
851   34     1986
852   47     1973
853   18     2002
854   43     1977
855   81     1939
856   -1       -1
857   23     1997
858  107     1913
859   62     1958
860  135     1885
861   10     2010
863   23     1997
864   -1       -1
866  239     1781
867    9     2011
868   13     2007
869   12     2008
870   36     1984
871   14     2006
875   54     1966
877   -1       -1
878   15     2005
879   51     1969
880   23     1997
881   12     2008
883   23     1997
884   15     2005
886  190     1830
887   12     2008
892   62     1958
893    9     2011
895   32     1988
896   21     1999
897   24     1996
898   10     2010
899   38     1982
900  107     1913
901   -1       -1
902   62     1958
904  107     1913
907  105     1915
909   56     1964
910   16     2004
911   21     1999
912   36     1984
913  108     1912
914   45     1975
916   24     1996
919   85     1935
920    8     2012
921   59     1961
924   -1       -1
926  145     1875
928   14     2006
929   31     1989
930   24     1996
931   43     1977
932  168     1852
933   18     2002
934   52     1968
935   62     1958
936   44     1976
938  145     1875
939   14     2006
940    9     2011
941    5     2015
942    5     2015
943   -1       -1
944   32     1988
945   13     2007
946   12     2008
947  169     1851
948    9     2011
949    3     2017
950  190     1830
951   14     2006
952   36     1984
953   -1       -1
955   53     1967

In [149]:
df['Job Description'][0]

'Data Scientist\nLocation: Albuquerque, NM\nEducation Required: Bachelor’s degree required, preferably in math, engineering, business, or the sciences.\nSkills Required:\nBachelor’s Degree in relevant field, e.g., math, data analysis, database, computer science, Artificial Intelligence (AI); three years’ experience credit for Master’s degree; five years’ experience credit for a Ph.D\nApplicant should be proficient in the use of Power BI, Tableau, Python, MATLAB, Microsoft Word, PowerPoint, Excel, and working knowledge of MS Access, LMS, SAS, data visualization tools, and have a strong algorithmic aptitude\nExcellent verbal and written communication skills, and quantitative analytical skills are required\nApplicant must be able to work in a team environment\nU.S. citizenship and ability to obtain a DoD Secret Clearance required\nResponsibilities: The applicant will be responsible for formulating analytical solutions to complex data problems; creating data analytic models to improve data metrics; analyzing customer behavior and trends; delivering insights to stakeholders, as well as designing and crafting reports, dashboards, models, and algorithms to make data insights actionable; selecting features, building and optimizing classifiers using machine learning techniques; data mining using state-of-the-art methods, extending organization’s data with third party sources of information when needed; enhancing data collection procedures to include information that is relevant for building analytic systems; processing, cleansing, and verifying the integrity of data used for analysis; doing ad-hoc analysis and presenting results in a clear manner; and creating automated anomaly detection systems and constant tracking of its performance.\nBenefits:\nWe offer competitive salaries commensurate with education and experience. We have an excellent benefits package that includes:\nComprehensive health, dental, life, long and short term disability insurance\n100% Company funded Retirement Plans\nGenerous vacation, holiday and sick pay plans\nTuition assistance\n\nBenefits are provided to employees regularly working a minimum of 30 hours per week.\n\nTecolote Research is a private, employee-owned corporation where people are our primary resource. Our investments in technology and training give our employees the tools to ensure our clients are provided the solutions they need, and our very high employee retention rate and stable workforce is an added value to our customers. Apply now to connect with a company that invests in you.'

In [ ]:
# Python
#Excel

In [152]:
df['python_yn']=df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
df.python_yn.value_counts()

<ipython-input-152-1919a8b978d8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['python_yn']=df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)

1    392
0    350
Name: python_yn, dtype: int64

In [153]:
df['excel_yn']=df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df.excel_yn.value_counts()

<ipython-input-153-191e30729f3a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['excel_yn']=df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)

1    388
0    354
Name: excel_yn, dtype: int64

In [155]:
df['spark_yn']=df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df.spark_yn.value_counts()

<ipython-input-155-010cac1a37b3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spark_yn']=df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)

0    575
1    167
Name: spark_yn, dtype: int64

In [165]:
df['aws_yn']=df['Job Description'].apply(lambda x: 1 if ' aws ' in x.lower() else 0)
df.aws_yn.value_counts()

<ipython-input-165-b0eb1a873fa7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['aws_yn']=df['Job Description'].apply(lambda x: 1 if ' aws ' in x.lower() else 0)

0    683
1     59
Name: aws_yn, dtype: int64

In [174]:
df['ml_yn']=df['Job Description'].apply(lambda x: 1 if 'machine learning' in x.lower() else 0)
df.ml_yn.value_counts()

<ipython-input-174-2a7ec3b951e4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ml_yn']=df['Job Description'].apply(lambda x: 1 if 'machine learning' in x.lower() else 0)

0    427
1    315
Name: ml_yn, dtype: int64

In [171]:
df.drop(['aws_yn'],axis=1,inplace=True)

C:\Users\progoti\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [173]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'hourly', 'employer_provided', 'min_salary', 'max_salary', 'avg_salary',
       'company_txt', 'state', 'same_state', 'age', 'python_yn', 'excel_yn',
       'spark_yn'],
      dtype='object')

In [184]:
print('Summary for SQL')
print(df['Job Description'].apply(lambda x: 1 if 'sql' in x.lower() else 0).value_counts())

print('Summary for database')
print(df['Job Description'].apply(lambda x: 1 if 'database' in x.lower() else 0).value_counts())

print('Summary for statistics')
print(df['Job Description'].apply(lambda x: 1 if 'statistics' in x.lower() else 0).value_counts())

print('Summary for math')
print(df['Job Description'].apply(lambda x: 1 if 'math' in x.lower() else 0).value_counts())

Summary for SQL
1    380
0    362
Name: Job Description, dtype: int64
Summary for database
0    493
1    249
Name: Job Description, dtype: int64
Summary for statistics
0    465
1    277
Name: Job Description, dtype: int64
Summary for math
0    457
1    285
Name: Job Description, dtype: int64

In [181]:
df['sql_yn']=df['Job Description'].apply(lambda x: 1 if 'sql' in x.lower() else 0)
df.sql_yn.value_counts()

<ipython-input-181-c32f9d3c7cec>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sql_yn']=df['Job Description'].apply(lambda x: 1 if 'sql' in x.lower() else 0)

1    380
0    362
Name: sql_yn, dtype: int64

In [ ]:
df['math_yn']=df['Job Description'].apply(lambda x: 1 if 'math' in x.lower() else 0)
df.math_yn.value_counts()

In [183]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'hourly', 'employer_provided', 'min_salary', 'max_salary', 'avg_salary',
       'company_txt', 'state', 'same_state', 'age', 'python_yn', 'excel_yn',
       'spark_yn', 'ml_yn', 'sql_yn'],
      dtype='object')

In [186]:
df_out=df.drop(['Unnamed: 0'],axis=1)

In [188]:
df_out.to_csv('salaray_data_cleaned.csv',index=False)

In [190]:
df_2=pd.read_csv('salaray_data_cleaned.csv')
df_2.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,avg_salary,company_txt,state,same_state,age,python_yn,excel_yn,spark_yn,ml_yn,sql_yn
0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,...,72.0,Tecolote Research\n,NM,0,47,1,1,0,1,0
1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,...,87.5,University of Maryland Medical System\n,MD,0,36,1,0,0,1,0
2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,...,85.0,KnowBe4\n,FL,1,10,1,1,1,1,1
3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,76.5,PNNL\n,WA,1,55,1,0,0,1,0
4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,...,114.5,Affinity Solutions\n,NY,1,22,1,1,0,1,1